"""Fix user_id types to BigInteger

Revision ID: 90a96ec4aa0a
Revises: 5d14be17f090
Create Date: 2026-07-30 11:24:36.544994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a96ec4aa0a'
down_revision: Union[str, None] = '5d14be17f090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
